max_obstacle_height: 0.60  # assume something like an arm is mounted on top of the robot

# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)

# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]  # if the robot is not circular
#footprint:  [[0.175, 0.175], [-0.175, 0.175], [-0.175, -0.175], [0.175, -0.175]]

footprint:  [[0.31, 0.31], [-0.31, 0.31], [-0.31, -0.31], [0.31, -0.31]]
#map_type: voxel


laser_layer:
  observation_sources:  scan 
  scan:
    data_type: LaserScan
    topic: myrobot1/laser_scan
    marking: true
    clearing: true
    min_obstacle_height: 0.05
    max_obstacle_height: 0.35
    obstacle_range: 6.0
    raytrace_range: 8.0

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns

static_layer:
  enabled:              true
  map_topic:             map
  subscribe_to_updates: true
  track_unknown_space:  true
  
#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:   3  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:      10 # max. distance from an obstacle at which costs are incurred for planning
