global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 5.0
   publish_frequency: 2.0
   static_map: true
   rolling_window: false
   transform_tolerance: 0.5

   plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"} #static map

     - {name: laser_layer,             type: "costmap_2d::ObstacleLayer"} #laser use on walls and objects

     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"} #inflation layer
